parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: wiki-test
    database_user: root
    database_password: mysqlpass
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 32fbd81cbe122f03176175104e1440f6f
    database_path: null
